// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGY4Va2dzyeW_yktCABw2Inx6zjz9MZ2o',
    appId: '1:648857501821:web:8b5eb2173d0cba8f7e3114',
    messagingSenderId: '648857501821',
    projectId: 'dosemate-72f52',
    authDomain: 'dosemate-72f52.firebaseapp.com',
    databaseURL: 'https://dosemate-72f52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dosemate-72f52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYzVnhMfjSeFE9cX3yoNML9NX524Mz_I',
    appId: '1:648857501821:android:b79eb620b47c13907e3114',
    messagingSenderId: '648857501821',
    projectId: 'dosemate-72f52',
    databaseURL: 'https://dosemate-72f52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dosemate-72f52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUSqTF8PBDl22Yi2rX7fqf_XNT8Uwu0M',
    appId: '1:648857501821:ios:bb3d32e8095d4ebb7e3114',
    messagingSenderId: '648857501821',
    projectId: 'dosemate-72f52',
    databaseURL: 'https://dosemate-72f52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dosemate-72f52.appspot.com',
    iosBundleId: 'com.example.dosemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUSqTF8PBDl22Yi2rX7fqf_XNT8Uwu0M',
    appId: '1:648857501821:ios:bb3d32e8095d4ebb7e3114',
    messagingSenderId: '648857501821',
    projectId: 'dosemate-72f52',
    databaseURL: 'https://dosemate-72f52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dosemate-72f52.appspot.com',
    iosBundleId: 'com.example.dosemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGY4Va2dzyeW_yktCABw2Inx6zjz9MZ2o',
    appId: '1:648857501821:web:f37904a14eeac13e7e3114',
    messagingSenderId: '648857501821',
    projectId: 'dosemate-72f52',
    authDomain: 'dosemate-72f52.firebaseapp.com',
    databaseURL: 'https://dosemate-72f52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dosemate-72f52.appspot.com',
  );

}